version: '3.5'
services:
  jenkins:
    #image: jenkinsci/blueocean:latest
    image: jenkins/jenkins:lts
    user: root
    container_name: jenkins
    volumes:
      - ./jenkins:/var/jenkins_home
      - /usr/bin/docker:/usr/bin/docker
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - proxynet

networks:
  proxynet:
    external:
      name: proxy_sites
